### ISSUE TITLE
Setup TLS details according to `user-agent`

### ISSUE THREAD

**Issue by Aubermean** [lexiforest/curl-impersonate#76]
https://github.com/Kikobeats/https-tls?tab=readme-ov-file

Setup TLS details according to `user-agent`

Could we use that project above to do things more dynamically?

**Comment by iffybug** [comment]
I don't have a plan to implement it here, because messing with strings in C can be a headache to me. But I do intend to implement this in curl_cffi, something like `impersonate="match"`.

Anyway, PRs are always welcome.
